"use client";

import Link from "next/link";
import { ArrowRight, Brain, Compass, Eye, ExternalLink, ImagePlus, Info, RefreshCw } from "lucide-react";
import { useEffect, useState } from "react";
import { PortraitRenderer, type PortraitSelection } from "@/components/portrait/PortraitRenderer";
import { PortraitErrorBoundary } from "@/components/portrait/PortraitErrorBoundary";
import { usePortrait, usePortraitHistory, useRefreshPortrait, useRefreshPortraitVisuals } from "@/hooks/usePortrait";
import { trackPortraitEvent } from "@/lib/portraitAnalytics";
import type { PortraitNode, PortraitThread, PortraitVisualSource } from "@/types/portrait";

function isNode(item: PortraitNode | PortraitThread): item is PortraitNode {
  return "domain" in item;
}

export default function ProfilePage() {
  const portrait = usePortrait();
  const history = usePortraitHistory();
  const refreshPortrait = useRefreshPortrait();
  const refreshVisuals = useRefreshPortraitVisuals();
  const [selected, setSelected] = useState<PortraitSelection | null>(null);
  const data = portrait.data;

  useEffect(() => {
    if (data?.snapshot_id) trackPortraitEvent("portrait_viewed", data.snapshot_id);
  }, [data?.snapshot_id]);

  return <div className="relative min-h-screen overflow-y-auto"><div className="mx-auto max-w-6xl p-4 sm:p-6 lg:p-12">
    <header className="mb-8 flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><p className="eyebrow mb-3 flex items-center gap-2"><Eye className="h-3.5 w-3.5" aria-hidden /> Profile</p><h1 className="atlas-title text-4xl sm:text-5xl">Your intellectual portrait.</h1><p className="mt-3 max-w-2xl text-sm leading-relaxed text-[var(--text-secondary)]">A human-centered view of the knowledge you have actually built in Lattice.</p></div><button type="button" onClick={() => refreshPortrait.mutate()} disabled={refreshPortrait.isPending} className="inline-flex items-center justify-center gap-2 self-start rounded-lg border border-[var(--border-subtle)] px-3 py-2 text-xs text-[var(--text-secondary)] hover:border-[var(--accent)] hover:text-[var(--accent)] disabled:opacity-50 sm:self-auto"><RefreshCw className={`h-3.5 w-3.5 ${refreshPortrait.isPending ? "animate-spin" : ""}`} aria-hidden />{refreshPortrait.isPending ? "Refreshing…" : "Refresh portrait"}</button></header>
    {refreshPortrait.isError && <p role="alert" className="-mt-4 mb-6 text-xs text-[var(--danger)]">Couldn&apos;t refresh the portrait. The last successful reading is unchanged.</p>}
    {portrait.isPending ? <div className="rounded-2xl border border-[var(--border-subtle)] bg-[var(--bg-surface)] p-10 text-sm text-[var(--text-secondary)]" aria-busy="true">Forming your portrait…</div> : portrait.isError ? <p role="alert" className="text-sm text-[var(--danger)]">Couldn&apos;t load your portrait.</p> : data && <>
      <div className="mb-6 grid gap-3 sm:grid-cols-3"><Stat label="Concepts" value={data.summary.concept_count} /><Stat label="Domains" value={data.summary.domain_count} /><Stat label="Active frontiers" value={data.summary.active_frontier_count} /></div>
      <div className="grid gap-6 lg:grid-cols-[minmax(0,1fr)_320px] lg:items-start"><div><PortraitErrorBoundary><PortraitRenderer portrait={data} onSelect={setSelected} /></PortraitErrorBoundary><div className="mt-4 flex flex-wrap items-center gap-3 text-xs text-[var(--text-secondary)]"><span className="flex items-center gap-1.5"><span className="h-2 w-2 rounded-full bg-[var(--accent)]" />Anchors inside</span><span className="flex items-center gap-1.5"><span className="h-2 w-2 rounded-full bg-[#c9a961]" />Bridges crossing</span><span className="flex items-center gap-1.5"><span className="h-2 w-2 rounded-full bg-[#7aa5d8]" />Frontier outside</span><span className="flex items-center gap-1.5"><span className="h-2 w-2 rounded-full bg-[#565e73]" />Dormant quieter</span></div><button type="button" onClick={() => refreshVisuals.mutate(data.snapshot_id)} disabled={refreshVisuals.isPending} className="mt-4 inline-flex items-center gap-2 rounded-md border border-[var(--border-subtle)] px-3 py-2 text-xs text-[var(--text-secondary)] hover:border-[var(--accent)] hover:text-[var(--accent)] disabled:opacity-50">{data.visual_sources.length ? <RefreshCw className={`h-3.5 w-3.5 ${refreshVisuals.isPending ? "animate-spin" : ""}`} /> : <ImagePlus className="h-3.5 w-3.5" />}{refreshVisuals.isPending ? "Finding sources…" : data.visual_sources.length ? "Refresh sourced visuals" : "Find sourced visuals"}</button>{refreshVisuals.isError && <p role="alert" className="mt-3 text-xs text-[var(--danger)]">Couldn&apos;t refresh sourced visuals. The current portrait is unchanged.</p>}</div><Inspector selected={selected} snapshotId={data.snapshot_id} /></div>
      <section className="mt-8 rounded-2xl border border-[var(--border-subtle)] bg-[var(--bg-surface)] p-6"><div className="flex items-start gap-3"><Info className="mt-0.5 h-4 w-4 shrink-0 text-[var(--accent)]" /><div><h2 className="text-sm font-semibold">A reading, not a personality test</h2><p className="mt-2 text-sm leading-relaxed text-[var(--text-secondary)]">{data.narrative}</p></div></div><div className="mt-5 flex flex-wrap gap-3"><Link href="/app/discovery" onClick={() => trackPortraitEvent("portrait_discovery_navigation", data.snapshot_id)} className="inline-flex items-center gap-2 rounded-md border border-[var(--border-subtle)] px-3 py-2 text-xs hover:border-[var(--accent)] hover:text-[var(--accent)]">Explore in Discovery <ArrowRight className="h-3.5 w-3.5" /></Link><Link href="/app/brain" onClick={() => trackPortraitEvent("portrait_brain_navigation", data.snapshot_id)} className="inline-flex items-center gap-2 rounded-md border border-[var(--border-subtle)] px-3 py-2 text-xs hover:border-[var(--accent)] hover:text-[var(--accent)]">Open the Brain <Brain className="h-3.5 w-3.5" /></Link></div></section>
      <section className="mt-6" aria-label="Textual portrait equivalent"><p className="eyebrow mb-4">Portrait index</p><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5"><IndexCard title="Anchors" items={data.anchors} /><IndexCard title="Bridges" items={data.bridges} /><IndexCard title="Frontier" items={data.frontiers} /><IndexCard title="Emerging" items={data.emerging_threads} /><IndexCard title="Dormant" items={data.dormant_threads} /></div></section>
      {history.data && history.data.length > 1 && <p className="mt-6 text-xs text-[var(--text-muted)]">{history.data.length} portrait snapshots · <Link href="/app/discovery" className="underline underline-offset-4 hover:text-[var(--accent)]">view evolution</Link></p>}
    </>}
  </div></div>;
}

function Stat({ label, value }: { label: string; value: number }) { return <div className="rounded-xl border border-[var(--border-subtle)] bg-[var(--bg-surface)] p-4"><p className="eyebrow">{label}</p><p className="mt-2 text-2xl font-semibold">{value}</p></div>; }

function Inspector({ selected, snapshotId }: { selected: PortraitSelection | null; snapshotId: string }) {
  if (!selected) return <aside className="rounded-2xl border border-dashed border-[var(--border-subtle)] bg-[var(--bg-surface)]/60 p-6 max-lg:sticky max-lg:bottom-4 max-lg:z-10 max-lg:backdrop-blur-sm"><p className="eyebrow mb-3">Inspector</p><h2 className="atlas-title text-2xl">Select a region</h2><p className="mt-2 text-sm leading-relaxed text-[var(--text-secondary)]">Click or focus a concept in the portrait to see why it appears and jump back to the Brain.</p></aside>;
  const { item, kind } = selected;
  if (kind === "visual") {
    const source = item as PortraitVisualSource;
    return <aside className="rounded-2xl border border-[var(--border-strong)] bg-[var(--bg-surface)] p-6 max-lg:sticky max-lg:bottom-4 max-lg:z-10 max-lg:backdrop-blur-sm" aria-live="polite"><p className="eyebrow mb-3">Visual source · {source.portrait_role}</p><h2 className="atlas-title text-2xl">{source.represents}</h2><p className="mt-3 text-sm leading-relaxed text-[var(--text-secondary)]">{source.asset.title}</p><dl className="mt-5 space-y-3 border-t border-[var(--border-subtle)] pt-4 text-xs"><div><dt className="text-[var(--text-secondary)]">Provider</dt><dd className="mt-1">{source.asset.provider}</dd></div><div><dt className="text-[var(--text-secondary)]">Rights</dt><dd className="mt-1">{source.asset.rights_class}{source.asset.license ? ` · ${source.asset.license}` : ""}</dd></div>{source.asset.creator && <div><dt className="text-[var(--text-secondary)]">Creator</dt><dd className="mt-1">{source.asset.creator}</dd></div>}{source.asset.institution && <div><dt className="text-[var(--text-secondary)]">Institution</dt><dd className="mt-1">{source.asset.institution}</dd></div>}{source.asset.date && <div><dt className="text-[var(--text-secondary)]">Date</dt><dd className="mt-1">{source.asset.date}</dd></div>}{source.asset.attribution_text && <div><dt className="text-[var(--text-secondary)]">Attribution</dt><dd className="mt-1 leading-relaxed">{source.asset.attribution_text}</dd></div>}</dl><a href={source.asset.source_url} target="_blank" rel="noreferrer" className="mt-5 inline-flex items-center gap-1.5 text-xs text-[var(--accent)] hover:underline">Open provenance <ExternalLink className="h-3.5 w-3.5" /></a><div className="mt-5 flex flex-wrap gap-3">{source.concept_ids[0] && <Link href={`/app/concepts/${source.concept_ids[0]}`} onClick={() => trackPortraitEvent("portrait_discovery_navigation", snapshotId, source.concept_ids[0])} className="inline-flex items-center gap-1.5 text-xs text-[var(--accent)] hover:underline">Open concept <ArrowRight className="h-3.5 w-3.5" /></Link>}<Link href={`/app/brain?portrait=${snapshotId}`} onClick={() => trackPortraitEvent("portrait_brain_navigation", snapshotId, source.asset_id)} className="inline-flex items-center gap-1.5 text-xs text-[var(--text-secondary)] hover:text-[var(--accent)]">View in Brain <Brain className="h-3.5 w-3.5" /></Link></div></aside>;
  }
  const portraitItem = item as PortraitNode | PortraitThread;
  const node = isNode(portraitItem) ? portraitItem : null;
  const threadHref = !isNode(portraitItem) && portraitItem.concept_ids[0] ? `/app/concepts/${portraitItem.concept_ids[0]}` : null;
  return <aside className="rounded-2xl border border-[var(--border-strong)] bg-[var(--bg-surface)] p-6 max-lg:sticky max-lg:bottom-4 max-lg:z-10 max-lg:backdrop-blur-sm" aria-live="polite"><p className="eyebrow mb-3">{kind.replace("_", " ")}</p><h2 className="atlas-title text-2xl">{portraitItem.name}</h2><p className="mt-3 text-sm leading-relaxed text-[var(--text-secondary)]">{portraitItem.reason}.</p><dl className="mt-5 space-y-3 border-t border-[var(--border-subtle)] pt-4 text-xs"><div className="flex justify-between gap-4"><dt className="text-[var(--text-secondary)]">Signal</dt><dd>{Math.round(portraitItem.score * 100)}%</dd></div>{node && <><div className="flex justify-between gap-4"><dt className="text-[var(--text-secondary)]">Mastery</dt><dd>{Math.round(node.mastery * 100)}%</dd></div><div><dt className="text-[var(--text-secondary)]">Domain</dt><dd className="mt-1">{node.domain}</dd></div>{node.connected_domains.length > 0 && <div><dt className="text-[var(--text-secondary)]">Connects</dt><dd className="mt-1 leading-relaxed">{node.connected_domains.join(" · ")}</dd></div>}</>}</dl><div className="mt-5 flex flex-wrap gap-3">{node && <Link href={`/app/concepts/${node.id}`} onClick={() => trackPortraitEvent("portrait_discovery_navigation", snapshotId, node.id)} className="inline-flex items-center gap-1.5 text-xs text-[var(--accent)] hover:underline">Open concept <ArrowRight className="h-3.5 w-3.5" /></Link>}{threadHref && <Link href={threadHref} onClick={() => trackPortraitEvent("portrait_discovery_navigation", snapshotId, portraitItem.id)} className="inline-flex items-center gap-1.5 text-xs text-[var(--accent)] hover:underline">Explore thread <ArrowRight className="h-3.5 w-3.5" /></Link>}<Link href={`/app/brain?portrait=${snapshotId}`} onClick={() => trackPortraitEvent("portrait_brain_navigation", snapshotId, portraitItem.id)} className="inline-flex items-center gap-1.5 text-xs text-[var(--text-secondary)] hover:text-[var(--accent)]">View in Brain <Brain className="h-3.5 w-3.5" /></Link></div></aside>;
}

function IndexCard({ title, items }: { title: string; items: (PortraitNode | PortraitThread)[] }) { return <div className="rounded-xl border border-[var(--border-subtle)] bg-[var(--bg-surface)] p-4"><p className="eyebrow mb-3">{title}</p>{items.length ? <ul className="space-y-2 text-sm">{items.slice(0, 4).map((item) => <li key={item.id} className="flex items-center justify-between gap-2"><span className="truncate">{item.name}</span><span className="font-mono text-[10px] text-[var(--text-muted)]">{Math.round(item.score * 100)}%</span></li>)}</ul> : <p className="text-xs text-[var(--text-secondary)]">Still forming.</p>}</div>; }
